Task/CC-9 - Create(CRUD)
Leopoldo-Medeiros/codecv6 pull request #12
Opened 2024-06-25 00:26 UTC by Leopoldo-Medeiros

2024-06-25 11:11 UTC, tschope requested changes

2024-06-25 11:11 UTC, tschope commented on resources/views/edit.blade.php
acredito q esse arquivo não deva existir

2024-06-25 11:11 UTC, tschope commented on resources/views/includes/admin/menu/admin.blade.php
> +<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
Não incluir CSS ou JS no meio dos arquivos. Usar sempre HEADER (CSS) ou FOOTER (JS) para fazer esses includes.

2024-06-25 11:11 UTC, tschope commented on resources/views/includes/admin/menu/admin.blade.php
> +<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
O projeto está usando bootstrap 5.4. Atenção a essa versão ao pegar templates ou exemplos na web

2024-06-25 11:11 UTC, tschope commented on resources/views/users/edit.blade.php
> +@extends('layouts.app')
ATENÇÃO! Você está trabalhando no admin, então você extende layouts.admin e não app q NÃO existe mais

2024-06-25 12:27 UTC, Leopoldo-Medeiros commented on resources/views/includes/admin/menu/admin.blade.php
> +<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
Peguei direto no site Bootstrap, porém pelo visto peguei a versão antiga. Vou consertar

2024-08-15 14:14 UTC, tschope commented
- [x] BUG: Não está atualizando nenhum campo proveniente do Profile (profiles)
- [x] BUG: Os botões estão brancos, quando passa o mouse fica azul

Melhorias: 

- [x] Não é possivel alterar senha e role (permissão) de nenhum usuario. 
- [x] Não é possivel deletar o usuario. Está apenas CRU, falta o D (CRUD)

2024-08-16 15:38 UTC, tschope requested changes

2024-08-22 15:27 UTC, tschope requested changes

2024-08-22 15:27 UTC, tschope commented on app/Http/Controllers/UsersController.php
> +            'birth_date' => 'nullable|date',
A validação do Item role, `'role' => 'nullable|exists:roles,id', ` deve continuar aqui. Ele só não deve ser usado dentro da tabela profile

2024-08-22 15:27 UTC, tschope commented on app/Http/Controllers/UsersController.php
Faça algumas validações de segurança. 
1. Se houver apenas 1 admin, não deletar esse usuario.
2. Não se auto deletar.

2024-08-22 15:27 UTC, tschope commented on database/migrations/2024_08_16_140342_add_role_to_profiles_table.php
remover esse arquivo, apesar dele ter sido criado de FORMA correta, em caso de adicionar o campo role, mas não é o caso aqui. Profiles não tem Roles

2024-08-22 15:27 UTC, tschope commented on resources/views/admin/dashboard.blade.php
> +                    <td>{{ $user->profile->role ?? 'N/A' }}</td>
Role não vem do Profile

2024-08-22 15:27 UTC, tschope commented on resources/views/users/create.blade.php
> +        </div>
Cade as roles?

2024-08-23 09:36 UTC, tschope requested changes

2024-08-23 09:36 UTC, tschope commented on app/Http/Controllers/UsersController.php
> +            'role' => $validated['role'] ?? null,
Não. Você tinha colocado o atualizar Role seguindo o Spatie Permissions. Assim não muda a permissão do usuario

2024-08-23 09:36 UTC, tschope commented on app/Models/User.php
> +    public function getRoleAttribute()
Função completamente errada. getRole e etc pertence a parte da Sptie Permissions, você não precisa dessa função.

2024-08-23 09:36 UTC, tschope commented on resources/views/users/create.blade.php
Eu acho que você deveria tenter concatenar 1 arquivo com a parte de adicionar e editar, assim você evita inconsistencias entre o arquivo de editar e adicionar. No momento os formularios estão diferentes

2024-08-23 09:36 UTC, tschope commented on resources/views/users/show.blade.php
> +            <p class="card-text"><strong>Role:</strong> {{ $user->profile->role }}</p>
Esse role aqui não faz sentido. Não pega a role baseada em Spatie Permissions

2024-08-26 11:44 UTC, tschope approved these changes

2024-08-26 11:45 UTC, merged