Task/cc 12
Leopoldo-Medeiros/codecv6 pull request #24
Opened 2024-10-17 16:45 UTC by Leopoldo-Medeiros

2024-10-22 13:18 UTC, tschope requested changes

2024-10-22 13:18 UTC, tschope commented on app/Http/Controllers/CourseController.php
> +    public function store(Request $request)
Você tem o CourseRequest, pq não usou?

2024-10-22 13:18 UTC, tschope commented on app/Http/Controllers/CourseController.php
> +    public function update(Request $request, Course $course)
Você tem o CourseRequest, pq não usou?

2024-10-22 13:18 UTC, tschope commented on app/Http/Requests/CourseRequest.php
> +class CourseRequest extends FormRequest
Arquivo aqui bonitão mas nunca usado? pq?

2024-10-22 13:18 UTC, tschope commented on database/migrations/2024_10_15_145007_create_courses_table.php
> +            $table->foreignId('user_id')->constrained()->onDelete('cascade');
Cuidado com isso aqui pq se você fizer cascade delete, quando você criar um curso e o funcionario sair da empresa, você deletar esse user, vai deletar o curso também? estranho

2024-10-30 16:32 UTC, tschope requested changes

2024-10-30 16:32 UTC, tschope commented on app/Http/Requests/CourseRequest.php
> +            'user_id' => 'required|exists:users,id',
No seu request você não passa o user_id, pq você está validando esse dado?

2024-10-30 16:32 UTC, tschope commented on app/Http/Controllers/CourseController.php
> +            'user_id' => auth()->id(), // Define o user_id como o id do usuário autenticado
Você valida o user_id no CourseRequest mas ai você usa o user_id da sessão atual, pq validar um dado q você não passou atraves de form?

2024-10-30 16:32 UTC, tschope commented on routes/web.php
> +    Route::resource('courses', CourseController::class);
courses está  sem proteção de admin, ou seja, qualquer usuario autenticado pode criar ou alterar o curso?

2024-10-30 23:29 UTC, Leopoldo-Medeiros commented on app/Http/Requests/CourseRequest.php
> +            'user_id' => 'required|exists:users,id',
Faz sentido. Nao sei pq fiz isso, uma vez que isso ta associado a Course, e nao a User... Aaff haha. Pérola

2024-10-31 09:30 UTC, tschope requested changes

2024-10-31 09:30 UTC, tschope commented on app/Http/Controllers/CourseController.php
> +            'description' => $validatedData['description'],
Você removeu o user mas agora o curso não está associado a user nenhum?

2024-10-31 09:30 UTC, tschope commented on app/Http/Controllers/CourseController.php
> +        $course->update($validatedData);
Perfeito, pq não fez a mesma coisa com o Create da linha 32? `Course::create($validatedData);`

2024-10-31 09:30 UTC, tschope commented on app/Http/Controllers/CourseController.php
> +        $course->update($validatedData);
Pq você não fez a mesma coisa na função create?

2024-10-31 09:30 UTC, tschope commented on app/Http/Requests/CourseRequest.php
> +
Sugiro adicionar a função 
```
/**
     * Prepare the data for validation.
     */
    protected function prepareForValidation()
    {
        // Adiciona o user_id do usuário logado aos dados da requisição
        $this->merge([
            'user_id' => Auth::id(),
        ]);
    }
```
Essa função vai trazer a variavel user_id para dentro do seu FormRequest e assim já preencher com o dado do usario logado. Use a `use Illuminate\Support\Facades\Auth;` no começo do codigo.

2024-10-31 09:30 UTC, tschope commented on app/Http/Requests/CourseRequest.php
> +            'description' => 'nullable|string',
complementando o user_id q está na função Pré validation, adicione o campo `'user_id' => 'required|exists:users,id',` para mante-lo no contexto. Agora ao user a função create ou update você passa direto os dados validados.

2024-10-31 09:30 UTC, tschope commented on routes/web.php
> +    Route::resource('courses', CourseController::class)->middleware('role:admin');
Pq não adicionar essa linha na dentro do grupo da linha 45?

2024-10-31 10:59 UTC, tschope requested changes

2024-10-31 10:59 UTC, tschope commented on app/Http/Controllers/CourseController.php
> +        $validatedData['user_id'] = auth()->id(); // Adiciona o user_id do usuário autenticado
Você já adiciona essa variavel lá na CourseRequest, linha 65, não tem pq fazer aqui também.

2024-10-31 15:10 UTC, tschope approved these changes

2024-11-01 14:30 UTC, merged