Task/CC-7
Leopoldo-Medeiros/codecv6 pull request #7
Opened 2024-05-28 00:39 UTC by Leopoldo-Medeiros

2024-05-28 12:51 UTC, tschope requested changes

2024-05-28 12:51 UTC, tschope commented on app/Http/Controllers/AuthController.php
>          return redirect('admin/login')->withErrors('Login details are not valid');
Por que ao entrar na tela de login esse login vem com um erro? Mesmo o usuario não tendo feito nenhuma ação.

2024-05-28 12:51 UTC, tschope commented on app/Http/Controllers/Controller.php
> -abstract class Controller
Por padrão é class abstract e não class Controller. E você declarou um use Resquest sem utilizar ele no arquivo em branco.

2024-05-28 12:51 UTC, tschope commented on routes/web.php
> +Route::get('/admin/login', [AuthController::class, 'index'])->name('login');
Remove essa rota admin. Login e logout unico para todos, oq  irá mudar será os acessos que você irá dar baseado na role do user

2024-05-28 12:51 UTC, tschope commented on routes/web.php
> +Route::post('/admin/login', [AuthController::class, 'customLogin'])->name('login.post');
customLogin eu não achei na controller Auth

2024-05-28 12:51 UTC, tschope commented on routes/web.php
> +Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Essa rota não existe

2024-05-28 12:51 UTC, tschope commented on routes/web.php
> +// User controllers
Todas essa rotas de usuarios precisaram ser protegidas. Você está fazem itens da CC-8 no merge da CC-7

2024-05-28 13:55 UTC, tschope requested changes

2024-05-28 13:55 UTC, tschope commented on routes/web.php
> +Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
Rota inexistente

2024-05-29 22:07 UTC, tschope requested changes

2024-05-29 22:07 UTC, tschope commented on app/Http/Controllers/AuthController.php
> -        return redirect('admin/login')->withErrors('Login details are not valid');
Ué, mas se a pessoa num loga no sistema, pq a senha está errada, pra onde ela vai? Não deveria voltar para a tela de login COM erro, pois ela tentou algo e não conseguiu?

2024-05-29 22:07 UTC, tschope commented on app/Http/Controllers/AuthController.php
>          return redirect('admin/login')->withSuccess('You are not allowed to access');
Ué, nesse momento a pessoa não está logada ou a sessão dela expirou, pq redireciona para login com Sucesso?!? Sucesso seria algo "positivo" como um login bem sucedido. Nesse caso aqui é com erro. Exemplo, sessão expirada

2024-05-29 22:07 UTC, tschope commented on routes/web.php
> -Route::post('/admin/login', [AdminController::class, 'customLogin'])->name('admin.login.post');
E como você loga se você removeu as rotas de login?

2024-05-31 09:54 UTC, tschope requested changes

2024-05-31 09:54 UTC, tschope commented on app/Http/Controllers/AuthController.php
> +        return redirect('admin/login')->with('You are not allowed to access');
Você pode usar o with, mas nesse casso é um erro. Qual o erro? O usuario precisa estar logado para ter acesso a essa página

2024-05-31 09:54 UTC, tschope commented on app/Http/Controllers/UserController.php
> +        return view('admin.dashboard', compact('users'));
Oxi, admin.dashboard? WHAT? Não seria user.index? Já falei. Você está juntando as tasks. Essa parte aqui não faz parte da task CC-7

2024-05-31 09:54 UTC, tschope commented on routes/web.php
> +Route::get('/admin/login', [AuthController::class, 'showLoginForm'])->name('login');
ué mas? rota duplicada? você tem a /login chamada admin.login e você tem a /admin/login chamada login? bugou.

2024-06-02 16:02 UTC, Leopoldo-Medeiros commented on routes/web.php
> +Route::get('/admin/login', [AuthController::class, 'showLoginForm'])->name('login');
Consertei. Parece que as rotas estão de acordo agora. Confere pra mim.

2024-06-03 18:59 UTC, tschope requested changes

2024-06-03 18:59 UTC, tschope commented on app/Http/Controllers/AuthController.php
> +        return redirect()->route('login.post');
post? não. Apenas login. Post é quando tem o envio do formulario. Não é o caso.

2024-06-03 18:59 UTC, tschope commented on routes/web.php
> +Route::get('/login', [AuthController::class, 'showLoginForm'])->name('login');
Revisar essas rotas. Rotas com o mesmo nome, rotas com path diferente que chamam a mesma função. Revisar

2024-06-04 10:19 UTC, tschope requested changes

2024-06-04 10:19 UTC, tschope commented on app/Http/Controllers/Admin/AdminController.php
> +class AdminController extends Controller
Você deve criar o menu no frontend. O if de menu deve ser feito direto no frontend. Não tem necessidade de uma Admin controller. Pode deletar esse arquivo

2024-06-04 10:19 UTC, tschope commented on app/Http/Controllers/AuthController.php
> +        return view('admin.login');
a função index faz exatamente o mesmo que a função showLoginForm. Não tem necessidade de ter duas funções fazendo a mesma coisa.

2024-06-04 10:19 UTC, tschope commented on routes/web.php
> +Route::get('/admin', [AuthController::class, 'dashboard'])->name('admin');
Novamente, você tem duas rotas fazendo a mesma coisa, pq? Remova essa rota. Deixar apenas a Dashboard.

2024-06-04 10:19 UTC, tschope commented on routes/web.php
> +Route::get('/admin/login', [AuthController::class, 'showLoginForm'])->name('admin.login');
rota repetida. /admin/login é a mesma que /login na linha 25. Remover essa rota.

2024-06-04 15:47 UTC, tschope approved these changes

2024-06-04 15:47 UTC, tschope commented
Approved

2024-06-04 18:30 UTC, merged