WIP - Painel Admin - Part 1
Leopoldo-Medeiros/codecv6 pull request #8
Opened 2024-06-05 15:37 UTC by Leopoldo-Medeiros

2024-06-11 08:01 UTC, tschope requested changes

2024-06-11 23:01 UTC, Leopoldo-Medeiros commented on resources/views/admin/dashboard.blade.php
> +                        <li class="list-group-item"><a href="{{ route('users.index') }}">My Courses</a></li>
Putz, verdade. Nesse caso, acredito que deveria ser "users.courses". Por conta dessa URL errada, eu fiz todo um processo voltado pra isso. Veja no PR se o que fiz faz sentido

2024-06-12 10:14 UTC, tschope requested changes

2024-06-12 10:14 UTC, tschope commented on routes/web.php
> +    Route::get('/users/{user}/courses', [CoursesController::class, 'index'])->name('users.courses');
Além da rota estar errada, remover qualquer referencia de outra task. Focar apenas na Task CC-8

2024-06-12 10:14 UTC, tschope commented on resources/views/users/courses.blade.php
Remover qualquer referencia de outra task. Apenas entregar coisas da CC-8. Deletar esse arquivo

2024-06-12 10:14 UTC, tschope commented on resources/views/layouts/admin.blade.php
Eu comentei de ter um layout apenas, você não deletou esse arquivo. Por favor deletar.

2024-06-12 10:14 UTC, tschope commented on resources/views/admin/dashboard.blade.php
> +                        <li class="list-group-item"><a href="{{ route('users.courses', auth()->user()) }}">My Courses</a></li>                        <li class="list-group-item"><a href="#">My Paths<
Remover qualquer referencia de outra task. Apenas entregar coisas da CC-8. Deletar esse arquivo

2024-06-12 10:14 UTC, tschope commented on resources/views/admin/clients.blade.php
Você criou uma view e você não utiliza ela em lugar algum. Delete esse arquivo.

2024-06-12 10:14 UTC, tschope commented on app/Http/Controllers/CoursesController.php
Remover qualquer referencia de outra task. Apenas entregar coisas da CC-8. Deletar esse arquivo

2024-06-12 15:49 UTC, tschope approved these changes
It's ok for now

2024-06-12 23:53 UTC, merged